version: "3"
services:
  node:
    image: flyxdocker/nodejschatapp:latest
    container_name: node2
    user: node
    working_dir: /home/node/app
    environment:
      - NODE_ENV=production
      - PORT=3000
    volumes:
      - ./:/home/node/app
    ports:
      - "80:3000"
